### ISSUE TITLE
Can't find `neutral_smpl_with_cocoplus_reg.txt` when running demo

### ISSUE THREAD

**Issue by BroderickHigby** [Arthur151/DSD-SATN#2]
```
        (envAlpha) (base) /DSD-SATN/src$ sh run.sh 
        ----------------
        Configuration:
        {'tab': 'single_h36m_g0', 'eval': True, 'eval_pw3d': False, 'online': False, 'videofile': './demo/demo.mp4', 'save_path_video': './result.avi', 'internet': False, 'test_single': True, 'inimg_dir': '/DSD-SATN/resources/image', 'visual_all': False, 'save_smpl_params': False, 'save_obj': False, 'with_kps': False, 'kps_type': 'kps_alpha', 'alpha_format': 'mpii', 'feature_num_deconv': 256, 'num_backbone_layers': 50, 'gmodel_path': '/DSD-SATN/trained_model/single_frame_dsd_model.pkl', 'dmodel_path': '/DSD-SATN/trained_model/D_single_frame_dsd_model.pkl', 'best_save_path': '/DSD-SATN/trained_model/single_frame_dsd_model.pkl', 'video': False, 'shuffle_aug': False, 'receptive_field': 9, 'self_attention': True, 'shuffle_smooth_loss': True, 'attention_layer': 2, 'epoch': 40, 'fine_tune': False, 'fit_epoch': 0, 'val_iter': 2000, 'lr': 0.0001, 'gpu': '0', 'batch_size': 16, 'val_batch_size': 16, 'nw': 6, 'features_type': 1, 'pix_format': 'NCHW', 'use_flip': False, 'normalize': True, 'video_clips_input': False, 'use_cropped_img': False, 'adjust_lr_factor': 0.1, 'with_mpjpeloss': True, 'with_constloss': False, 'best': 48.0, 'best_mpjpe': 68.0, 'best_pw3d': 48.0, 'best_mpjpe_pw3d': 68.0, 'dataset_rootdir': '/DSD-SATN/../../dataset/', 'dataset': 'h36m', 'with_h36m': True, 'with_up': False, 'with_mpii': False, 'with_aich': False, 'with_mpv': False, 'with_iv': False, 'with_pa': False, 'with_df': False, 'use_all_subject': False, 'eval_protocol': 1, 'kp3d_num': 14, 'kp3d_24': False, 'eval_with_single_frame_network': False, 'high_resolution': False, 's': 1, 'save_features': False, 'get_features': False, 'save_best_folder': '/DSD-SATN/trained_model/', 'log_path': '/DSD-SATN/src/log/', 'hmr_video_mode': False, 'coco25_regressor_path': '/DSD-SATN/model/neutral_smpl_with_cocoplustoesankles_reg.pkl', 'total_param_count': 85, 'smpl_mean_param_path': '/DSD-SATN/model/neutral_smpl_mean_params.h5', 'smpl_model': '/DSD-SATN/model/neutral_smpl_with_cocoplus_reg.txt', 'h36m_path': '/media/sunyu/sunyu1/dataset/h36m', 'aich_path': '/media/sunyu/sunyu1/dataset/ai_challenger', 'mpii_path': '/media/sunyu/sunyu1/dataset/mpii', 'up_path': '/media/sunyu/sunyu1/dataset/UP', 'pw3d_path': '/media/sunyu/sunyu1/dataset/3DPW', 'mosh_path': '/media/sunyu/sunyu1/dataset/mosh_gen', 'regre_weight': 10.0, 'pose_weight': 20.0, 'shape_weight': 0.6, 'mpjpe_weight': 60.0, 'pampjpe_weight': 80.0, 'kp_weight': 10.0, 'const_weight': 0, 'disc_weight': 0.1, 'shuffle_weight': 0, 'filter_widths': [3, 3], 'features_channels': 512, 'feature_name': 'bilinear_features', 'eval_mode': 'all'}
        ----------------
        with_kps: False type: kps_alpha format: mpii
        datasets: h36m
        ----------------
        start building modle.
        Traceback (most recent call last):
          File "test.py", line 108, in <module>
            main()
          File "test.py", line 104, in main
            demo = Demo()
          File "test.py", line 9, in __init__
            self._build_model()
          File "/DSD-SATN/src/base.py", line 56, in _build_model
            generator = get_pose_net()
          File "/DSD-SATN/src/model/model.py", line 278, in get_pose_net
            model = PoseResNet(block_class, layers, baseline0=baseline0, baseline=baseline, baseline2=baseline2,kp3d=kp3d,video_clips_input=video_clips_input)
          File "/DSD-SATN/src/model/model.py", line 160, in __init__
            self.smpl = SMPL(args.smpl_model, joint_type = 'lsp',obj_saveable = True)
          File "/DSD-SATN/src/utils/SMPL.py", line 26, in __init__
            with open(self.model_path, 'r') as reader:
        FileNotFoundError: [Errno 2] No such file or directory: '/DSD-SATN/model/neutral_smpl_with_cocoplus_reg.txt'

```

installed the requirements.txt file and ran the demo. on Ubuntu 16.04, running a 1070

**Comment by BroderickHigby** [comment]
i had to download the models. Thanks for making this

**Comment by xianzhongma** [comment]
> i had to download the models. Thanks for making this

Hi, I cannot find the files, too. And the link in README.md has expired. Could you share a copy of the files to me? Thanks!

**Comment by Arthur151** [comment]
Sorry about that, I have updated the new google drive and uploaded all files that I can still find. 
While this repository is no longer maintained. Please refer to ROMP for more functions.
